create table person (
    person_id int generated by default as identity primary key,
    full_name varchar(100) not null unique,
    year_of_birth int not null
);


create table book (
    book_id int generated by default as IDENTITY primary key,
    person_id int references person (person_id) on delete set null,
    title varchar(100) not null,
    author varchar(100) not null,
    year int,
    book_get_date date
);